name: 01 Regression tests

on:
  workflow_dispatch:
    inputs:
      node_rev:
        description: "cardano-node revision (default: master HEAD)"
        required: false
      cluster_era:
        type: choice
        description: "Cluster era"
        options:
        - babbage
        default: babbage
      tx_era:
        type: choice
        description: "Tx era"
        options:
        - default
        - babbage
        - alonzo
        - mary
        - allegra
        - shelley
        default: default
      enable_p2p:
        type: boolean
        default: false
        description: "Enable P2P network topology"
      skip_long:
        type: boolean
        default: false
        description: "Skip long running tests"
      fast_cluster:
        type: boolean
        default: false
        description: "Start cluster directly in target era"
      testrun_name:
        required: false
        description: "Test run name (internal)"
      skip_passed:
        type: boolean
        default: false
        description: "Skip tests that already passed (internal)"

run-name: ${{ inputs.testrun_name && 'Run:' || ''}} ${{ inputs.testrun_name }} ${{ (inputs.testrun_name && inputs.skip_passed) && ':repeat:' || '' }}

jobs:
  regression_tests:
    # reusable workflow from local repo and same branch as this config
    uses: ./.github/workflows/regression_reusable.yaml
    with:
      node_rev: ${{ inputs.node_rev }}
      cluster_era: ${{ inputs.cluster_era }}
      tx_era: ${{ inputs.tx_era }}
      enable_p2p: ${{ inputs.enable_p2p }}
      skip_long: ${{ inputs.skip_long }}
      fast_cluster: ${{ inputs.fast_cluster }}
      testrun_name: ${{ inputs.testrun_name }}
      skip_passed: ${{ inputs.skip_passed }}
    secrets:
      TCACHE_BASIC_AUTH: ${{ secrets.TCACHE_BASIC_AUTH }}
      TCACHE_URL: ${{ secrets.TCACHE_URL }}
